CREATE TABLE `user` (
`id` INT ( 11 ) NOT NULL AUTO_INCREMENT,
`username` VARCHAR ( 255 ) COLLATE utf8_bin DEFAULT NULL,
`password` VARCHAR ( 255 ) COLLATE utf8_bin DEFAULT NULL,
`phone` VARCHAR ( 255 ) COLLATE utf8_bin DEFAULT NULL,
`email` VARCHAR ( 255 ) COLLATE utf8_bin DEFAULT NULL,
`sex` VARCHAR ( 255 ) COLLATE utf8_bin DEFAULT NULL,
`birthday` datetime DEFAULT NULL,
PRIMARY KEY ( `id` ) USING BTREE 
) ENGINE = InnoDB  DEFAULT CHARSET = utf8 COLLATE = utf8_bin ROW_FORMAT = DYNAMIC;